# Generated by Django 5.1.4 on 2025-01-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
