# Generated by Django 5.1.4 on 2025-01-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypedia", "0003_course_owner_lesson_owner_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="user",
            new_name="owner",
        ),
    ]
