# Generated by Django 5.1.4 on 2025-01-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypedia", "0006_alter_lesson_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(default="unpaid", max_length=50, verbose_name="Статус"),
        ),
    ]
