# Generated by Django 5.1.4 on 2025-01-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypedia", "0007_payment_link_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии"),
        ),
    ]
