# Generated by Django 5.1.4 on 2025-01-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypedia", "0008_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Сумма оплаты"),
        ),
    ]
