# Generated by Django 5.1.4 on 2025-01-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypedia", "0009_alter_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
